services:
  - type: web
    name: gym-management-system
    runtime: node
    repo: https://github.com/lordshiva09/GYM-MANAGEMENT-SYSTEM
    branch: master
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3001
